### ISSUE TITLE
Auto npm publish

### ISSUE THREAD

**Issue by PierrickP** [Lendix/lemonway#13]
Add `.travis.yml` (free for open source)

```yml
language: node_js

node_js:
  - "4"
  - "6"

notifications:
  email: false

deploy:
  - provider: npm
    email: email@email.com
    api_key:
      secure: SECURED_TOKEN
    skip_cleanup: true
    on:
      branch: master
```

*node_js*: i select LTS and latest
*SECURED_TOKEN*: cmd `travis encrypt YOUR_API_KEY` (https://docs.travis-ci.com/user/deployment/npm)
